-- Migration for new features: Edit Window, Bookmarks, Me Too, Threads, Notifications
-- Run this in Supabase SQL Editor

-- 1. Add new columns to messages table
DO $$
BEGIN
  -- Add edited_at column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'messages' 
    AND column_name = 'edited_at'
  ) THEN
    ALTER TABLE public.messages ADD COLUMN edited_at timestamp with time zone;
  END IF;

  -- Add is_edited column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'messages' 
    AND column_name = 'is_edited'
  ) THEN
    ALTER TABLE public.messages ADD COLUMN is_edited boolean default false;
  END IF;

  -- Add thread_id column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'messages' 
    AND column_name = 'thread_id'
  ) THEN
    ALTER TABLE public.messages ADD COLUMN thread_id bigint;
  END IF;

  -- Add me_too_count column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'messages' 
    AND column_name = 'me_too_count'
  ) THEN
    ALTER TABLE public.messages ADD COLUMN me_too_count integer default 0;
  END IF;

  -- Add me_too_users column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'messages' 
    AND column_name = 'me_too_users'
  ) THEN
    ALTER TABLE public.messages ADD COLUMN me_too_users text[] default '{}'::text[];
  END IF;
END $$;

-- 2. Create index for thread queries
CREATE INDEX IF NOT EXISTS idx_messages_thread_id ON public.messages(thread_id) WHERE thread_id IS NOT NULL;

-- 3. Create bookmarks table
CREATE TABLE IF NOT EXISTS public.bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  message_id bigint references public.messages(id) ON DELETE CASCADE not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  UNIQUE(user_id, message_id)
);

-- 4. Create indexes for bookmarks
CREATE INDEX IF NOT EXISTS idx_bookmarks_user_id ON public.bookmarks(user_id);
CREATE INDEX IF NOT EXISTS idx_bookmarks_message_id ON public.bookmarks(message_id);

-- 5. Create notifications table
CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  type text not null,
  message_id bigint references public.messages(id) ON DELETE CASCADE,
  from_username text,
  content text,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Create indexes for notifications
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON public.notifications(user_id, is_read);

-- 7. Enable RLS on new tables
ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- 8. Drop existing policies if they exist
DROP POLICY IF EXISTS "Bookmarks are viewable by owner" ON public.bookmarks;
DROP POLICY IF EXISTS "Users can insert their own bookmarks" ON public.bookmarks;
DROP POLICY IF EXISTS "Users can delete their own bookmarks" ON public.bookmarks;

DROP POLICY IF EXISTS "Notifications are viewable by owner" ON public.notifications;
DROP POLICY IF EXISTS "Anyone can insert notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can update their own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can delete their own notifications" ON public.notifications;

-- 9. Create RLS policies for bookmarks
CREATE POLICY "Bookmarks are viewable by owner"
  ON public.bookmarks FOR SELECT
  USING ( auth.uid() = user_id );

CREATE POLICY "Users can insert their own bookmarks"
  ON public.bookmarks FOR INSERT
  WITH CHECK ( auth.uid() = user_id );

CREATE POLICY "Users can delete their own bookmarks"
  ON public.bookmarks FOR DELETE
  USING ( auth.uid() = user_id );

-- 10. Create RLS policies for notifications
CREATE POLICY "Notifications are viewable by owner"
  ON public.notifications FOR SELECT
  USING ( auth.uid() = user_id );

CREATE POLICY "Anyone can insert notifications"
  ON public.notifications FOR INSERT
  WITH CHECK ( true );

CREATE POLICY "Users can update their own notifications"
  ON public.notifications FOR UPDATE
  USING ( auth.uid() = user_id );

CREATE POLICY "Users can delete their own notifications"
  ON public.notifications FOR DELETE
  USING ( auth.uid() = user_id );

-- 11. Enable Realtime for new tables
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE bookmarks;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Migration complete!
-- New features enabled:
-- 1. Edit Window (2 minutes) - Users can edit their messages
-- 2. Bookmarks - Users can save messages for later
-- 3. Me Too - Users can show support for confessions
-- 4. Confession Threads - Continue confession conversations
-- 5. Notifications - Get notified of interactions
