-- Create the messages table
create table public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  college text not null,
  user_id uuid references auth.users not null,
  username text not null,
  avatar_color text not null,
  type text default 'text'::text,
  aura integer default 0,
  flags integer default 0,
  reactions jsonb default '{}'::jsonb,
  reports jsonb default '{}'::jsonb,
  reply_to_id bigint references public.messages(id),
  hashtags text[] default '{}'::text[]
);

-- Create index for hashtag queries
CREATE INDEX idx_messages_hashtags ON public.messages USING GIN(hashtags);

-- Track active hashtag groups (top 5 per college)
create table public.hashtag_groups (
  id bigint generated by default as identity primary key,
  college text not null,
  hashtag text not null,
  message_count integer default 0,
  last_message_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid references auth.users,
  UNIQUE(college, hashtag)
);

-- Enable Row Level Security (RLS)
alter table public.messages enable row level security;
alter table public.hashtag_groups enable row level security;

-- Create Policy: Allow anyone to read messages (Public)
create policy "Public messages are viewable by everyone"
  on public.messages for select
  using ( true );

-- Create Policy: Allow authenticated users to insert messages
create policy "Users can insert their own messages"
  on public.messages for insert
  with check ( auth.uid() = user_id );

-- Create Policy: Allow anyone to update aura/flags (Game Mechanics)
-- In a real app, you'd want stricter controls, but for this MVP:
create policy "Anyone can update messages (likes/flags)"
  on public.messages for update
  using ( true );

-- Create Policy: Allow admins (or anyone for MVP) to delete messages
-- ideally this would be restricted to specific user IDs
create policy "Anyone can delete messages"
  on public.messages for delete
  using ( true );

-- Hashtag Groups Policies
create policy "Hashtag groups are viewable by everyone"
  on public.hashtag_groups for select
  using ( true );

create policy "Anyone can insert hashtag groups"
  on public.hashtag_groups for insert
  with check ( true );

create policy "Anyone can update hashtag groups"
  on public.hashtag_groups for update
  using ( true );

create policy "Anyone can delete hashtag groups"
  on public.hashtag_groups for delete
  using ( true );

-- Enable Realtime
alter publication supabase_realtime add table messages;
alter publication supabase_realtime add table hashtag_groups;
